name: Create release

on:
  push:
    branches:
        - '**'
    tags:
      - 'v*'

jobs:
  generate-release-doc:
    runs-on: ubuntu-latest
    name: Generate release documentation and gerbers
    env:
      BOARD_NAME: balanced-receiver
      OUTPUT_DIR: outputs
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify title block
        env:
          TITLE_BLOCK_AUTHOR: ${{ vars.PROJECT_AUTHOR }}
          TITLE_BLOCK_REVISION: ${{ github.sha }}
          TITLE_BLOCK_BASE_REPOSITORY: github.com/${{ github.repository_owner }}
          TITLE_BLOCK_REPOSITORY: ${{ github.server_url }}/${{github.repository}}
          TITLE_BLOCK_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          TITLE_BLOCK_PROJECT_NAME_SHORT: ${{ vars.PROJECT_NAME_SHORT }}
        run: |
          TITLE_BLOCK_DATE=$(date +'%Y.%m.%d') python3 scripts/update_title_block.py 

      - name: Generate release documentation
        run: |
          mkdir -p ${OUTPUT_DIR}
          docker run -v ${GITHUB_WORKSPACE}:/kikit --entrypoint kicad-cli yaqwsx/kikit \
            sch export pdf --output "/kikit/${OUTPUT_DIR}/${BOARD_NAME}.pdf" "/kikit/${BOARD_NAME}.kicad_sch"    
          docker run -v ${GITHUB_WORKSPACE}:/kikit --entrypoint kicad-cli yaqwsx/kikit \
            sch export pdf --output "/kikit/${OUTPUT_DIR}/${BOARD_NAME}_bom.csv" "/kikit/${BOARD_NAME}.kicad_sch"

      - name: Generate gerber files
        env:
          FABHOUSE: jlcpcb
        run: |
          docker run -v ${GITHUB_WORKSPACE}:/kikit yaqwsx/kikit fab ${FABHOUSE} --no-drc "${BOARD_NAME}.kicad_pcb" .
          mv gerbers.zip ${OUTPUT_DIR}/${BOARD_NAME}_gerbers.zip

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: balanced-receiver
          path: outputs
        